# Generated by Django 3.0.6 on 2020-05-30 18:45

from django.db import migrations
def create_data(apps, schema_editor):
    Artist = apps.get_model('gallery', 'Artist')
    Artist(first_name="Artist 001", last_name="Artist 001", email="artist001@email.com", about= "Artist 001 description").save()

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
